server:
  port: 8080
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      schema: autenticacion
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      connect-timeout: 5s

  profiles:
    include: null
    active: prod
logging:
  config: classpath:log4j2-prod.yaml
  level:
    root: info
    co.com.pragma: debug
    org.springframework.security: debug # Added for Spring Security debug logs
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds
  excluded-paths:
    - /api/v1/login
    - /swagger-ui.html
    - /swagger-ui/**
    - /webjars/**
    - /v3/api-docs/**

security:
  rules:
    authorization:
      - path: /api/v1/usuarios
        method: POST
        managerBeanName: postUserCreationAuthorizationManager
      - path: /api/v1/usuarios
        method: GET
        managerBeanName: userAuthorizationManager
