server:
  port: 8080
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya
    username: ${DB_USER}
    password: ${DB_SECRET}
    properties:
      schema: autenticacion
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      connect-timeout: 5s

  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  config: classpath:profiles/web-service.yaml
jwt:
  secret: "your-secret-key-that-is-at-least-256-bits-long"
  expiration: 3600000 # 1 hour in milliseconds